### ISSUE TITLE
Project Roadmap (Outline)

### ISSUE THREAD

**Issue by neoncitylights** [wandering-app/app#113]
> [!NOTE]
> Please note that this roadmap is not fixed and will continually update! Thank you.

## Design and identity
This focuses on creating a design system, which will help compose the branding identity and act as the foundation for the overall UI/UX of the web application.

 - [ ] Typefaces for heading, body, and monospace
 - [ ] Color palette
 - [ ] Icons
 - [ ] Organization name, application name
 - [ ] Logo (including favicon)
 - [ ] Mission statement

## Dynamic routing
[Dynamic routing](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes) enables going to different pages with custom parameters.

 - [ ] US state page
   - Route: `state/[stateCode]/route.tsx`
     - `[stateCode]` is a parameter that can accept a 2-letter US state code
     - Example page: `website.com/state/TX`
 - [ ] US state legislator page
   - Routes:
     - `state/[stateCode]/senate/[person]/route.tsx`
     - `state/[stateCode]/house/[person]/route.tsx`
     - `[person]` is a parameter that can accept a person's first name and last name. This is a sub-route of a state. The format is `{lastname}-{firstname}`
     - Example page: `website.com/state/CA/senate/feinstein-dianne`
 - [ ] US state law page
   - Route: `state/[stateCode]/law/[lawCode]/route.tsx`
     - `[lawCode]` is a parameter that can accept a unique identifier of a law
     - Example page: `website.com/state/WA/law/SR8603`
 - [ ] US federal law page
   - Route: TBD
 - [ ] US congress member page
   - Route: TBD
 - [ ] Public transit page
   - Route: TBD
